# Generated by Django 2.2.1 on 2021-01-26 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogify', '0002_auto_20210126_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='username',
        ),
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
