# Generated by Django 2.2.1 on 2021-01-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogify', '0003_auto_20210126_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
