# Generated by Django 2.2.1 on 2021-01-30 14:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogify', '0008_blogs_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
