# Generated by Django 2.2.1 on 2021-01-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogify', '0013_auto_20210130_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='date_posted',
        ),
    ]
